services:
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_URI=redis://redis
      - GEMINI_API_KEY=YourGeminiApiKey

    depends_on:
      - redis
